"""
Ambiguity Register — Footbolzano 2025 v1
Provisional interpretations for unclear rules.
"""

AMBIGUITIES = [
    {
        "id": "AMB-001",
        "rule_id": "EXEC_ORDER",
        "title": "Execution order for concurrent effects",
        "description": "When multiple perks/items affect the same player simultaneously, the exact stacking order is not specified in the rulebook.",
        "provisional_interpretation": "Apply in this order: (1) zeroing effects, (2) division/halving, (3) multiplication, (4) flat additions. Within each category, apply by item cost descending (higher-cost items first).",
        "source_citation": "https://footbolzano.com/rules/ — Attacks section (no explicit stacking order defined)",
        "status": "open",
        "requires_commissioner": True,
    },
    {
        "id": "AMB-002",
        "rule_id": "PERK_MILITIA_SCOPE",
        "title": "Militia: does it apply before or after other player effects?",
        "description": "Militia grants +20% to 'all active players' scores'. Ambiguous whether this means +20% to raw or to adjusted scores, and whether it applies before or after item-based adjustments.",
        "provisional_interpretation": "Militia applies to adjusted player scores (after all item effects), treating it as a teamwide percentage in step 11.",
        "source_citation": "https://footbolzano.com/rules/ — Soldier Perk: Militia",
        "status": "open",
        "requires_commissioner": True,
    },
    {
        "id": "AMB-003",
        "rule_id": "PERK_CALL_OF_WILD_DOUBLING",
        "title": "Call of the Wild: does doubling stack with other multipliers?",
        "description": "Call of the Wild doubles players facing a chosen NFL team. Unclear if this stacks multiplicatively with e.g. Martyr or Ivory Tower Defense.",
        "provisional_interpretation": "Call of the Wild doubling stacks multiplicatively with other multipliers (applied in order).",
        "source_citation": "https://footbolzano.com/rules/ — Druid Perk: Call of the Wild",
        "status": "open",
        "requires_commissioner": True,
    },
    {
        "id": "AMB-004",
        "rule_id": "PERK_OUT_OF_COLLATERAL_DATA",
        "title": "Out of Collateral: requires passing yards, not available in all providers",
        "description": "Out of Collateral requires QB passing yards to determine auto-win/loss/bonus. MockLiveProvider only provides total raw score.",
        "provisional_interpretation": "When passing yards data is unavailable, the perk is held in abeyance and a commissioner ruling is required.",
        "source_citation": "https://footbolzano.com/rules/ — Gambler Perk: Out of Collateral",
        "status": "open",
        "requires_commissioner": True,
    },
    {
        "id": "AMB-005",
        "rule_id": "PERK_LEVERGE_LAST_WEEK_ZERO",
        "title": "Leverage: what counts as 'last week > 0'?",
        "description": "Leverage requires 'last week > 0' to be eligible. Unclear if a player who was on bye (scored 0 due to bye) disqualifies.",
        "provisional_interpretation": "A player on bye (0 due to bye, not actual play) is treated as having no previous week score for Leverage purposes — does not qualify.",
        "source_citation": "https://footbolzano.com/rules/ — Gambler Perk: Leverage",
        "status": "open",
        "requires_commissioner": True,
    },
    {
        "id": "AMB-006",
        "rule_id": "DEATH_DROP_TIMING",
        "title": "Dead player drop timing: immediate vs. before next week",
        "description": "Rulebook says 'killed players must be dropped immediately' but doesn't clarify if this means before the final score is locked or before next week's roster lock.",
        "provisional_interpretation": "Dead players are removed from scoring for the current week only if killed before the game ends. If killed at week's end (Martyr, Soul Reaper), they do not affect the current week's score.",
        "source_citation": "https://footbolzano.com/rules/ — Quests: Dead Players",
        "status": "open",
        "requires_commissioner": True,
    },
    {
        "id": "AMB-007",
        "rule_id": "GOLD_PROVISIONAL_TIMING",
        "title": "When are gold earnings confirmed vs. provisional?",
        "description": "Gold earned from race income is based on raw scores. Since raw scores can be corrected by CBS after the fact, when does race gold become final?",
        "provisional_interpretation": "Race gold is provisional until stat corrections window closes (Tuesday 3PM PT per scoring validation rules). This matches the general finalization timeline.",
        "source_citation": "https://footbolzano.com/rules/ — Scoring Validation section",
        "status": "open",
        "requires_commissioner": False,
    },
    {
        "id": "AMB-008",
        "rule_id": "ATK_WOODEN_CLUB_ROSTER_POSITION",
        "title": "Wooden Club: 'opponent's player in that position' — what if opponent has no player at that position?",
        "description": "Wooden Club says player scores max(own, opponent's, 10). If opponent has no player at that position, what is 'opponent's player' score?",
        "provisional_interpretation": "If opponent has no player at the designated position, treat opponent's score for that position as 0.",
        "source_citation": "https://footbolzano.com/rules/ — Weapon Store: Wooden Club",
        "status": "open",
        "requires_commissioner": True,
    },
]
