"""
Rule catalog — structured metadata for all implemented rules.
Each rule has: rule_id, rule_name, version, source_citation, category,
trigger_timing (execution step), calculation, explanation_template,
approval_status.
"""

RULES_CATALOG = [
    # ── Validation ────────────────────────────────────────────────────────────
    {
        "rule_id": "VAL_DUPLICATE_PLAYER",
        "rule_name": "Duplicate Player Validation",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Rosters",
        "category": "validation",
        "trigger_timing": 1,
        "calculation": "Flag error if same player appears twice in starting lineup",
        "explanation_template": "Player {player} appears more than once in {team}'s lineup.",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_INVALID_BYE",
        "rule_name": "Cannot Attack Bye Player",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Attacks: 'You may not attack a player you know will not play (bye, IR, or suspended)'",
        "category": "validation",
        "trigger_timing": 5,
        "calculation": "Invalidate attack if target is on bye",
        "explanation_template": "{player} is on bye. Attack invalid.",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_INVALID_DEAD",
        "rule_name": "Cannot Attack Dead Player",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Quests: Dead Players",
        "category": "validation",
        "trigger_timing": 5,
        "calculation": "Invalidate attack if target is dead",
        "explanation_template": "{player} is dead. Attack invalid.",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_INVALID_ARROWS_DIGIT",
        "rule_name": "Arrows Attack Eligibility: Ones Digit Check",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Weapon Store: Wooden Arrows / Steel Arrows",
        "category": "validation",
        "trigger_timing": 5,
        "calculation": "Wooden Arrows: target previous-week ones digit 0–3. Steel Arrows: 0–5.",
        "explanation_template": "{player}'s previous-week ones digit {digit} out of range for {weapon}.",
        "approval_status": "confirmed",
    },
    # ── Protections ───────────────────────────────────────────────────────────
    {
        "rule_id": "ATK_BLOCKED_PROTECTION",
        "rule_name": "Protection Blocks Wooden Attack",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Warrior Perk: Tower Shield / Gambler Perk: Leverage",
        "category": "protection",
        "trigger_timing": 5,
        "calculation": "If target has wooden-weapon immunity and attack is wooden, block attack",
        "explanation_template": "{player} is protected by {source}. Wooden attack has no effect.",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_BLOCKED_ANTIDOTE",
        "rule_name": "Antidote Blocks Basic Poison",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Alchemist Perk: Antidote",
        "category": "protection",
        "trigger_timing": 5,
        "calculation": "If target team has Antidote and attack is basic poison, block",
        "explanation_template": "{team} has Antidote. Basic poison blocked.",
        "approval_status": "confirmed",
    },
    # ── Attacks: Player Effects ───────────────────────────────────────────────
    {
        "rule_id": "ATK_WOODEN_SWORD",
        "rule_name": "Wooden Sword",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Weapon Store: Wooden Sword ($70, Humans)",
        "category": "attack_player_multiplier",
        "trigger_timing": 8,
        "calculation": "target.score = target.score / 2",
        "explanation_template": "Wooden Sword: {player} score {before} ÷ 2 = {after}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_STEEL_SWORD",
        "rule_name": "Steel Sword",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Armory: Steel Sword ($200, requires Wooden Sword)",
        "category": "attack_zeroing",
        "trigger_timing": 8,
        "calculation": "target.score = 0",
        "explanation_template": "Steel Sword: {player} score {before} → 0",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_BASIC_POISON",
        "rule_name": "Basic Poison",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — General Store: Poison ($30)",
        "category": "attack_player_multiplier",
        "trigger_timing": 8,
        "calculation": "target.score = target.score / 2",
        "explanation_template": "Basic Poison: {player} score {before} ÷ 2 = {after}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_SUPER_POISON",
        "rule_name": "Super Poison",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Apothecary: Super Poison ($120, requires Apprentice Apothecary)",
        "category": "attack_player_multiplier",
        "trigger_timing": 8,
        "calculation": "highest_scorer.score = highest_scorer.score / 2",
        "explanation_template": "Super Poison: {player} (highest scorer {before}) ÷ 2 = {after}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_TWIN_WOODEN_DAGGERS",
        "rule_name": "Twin Wooden Daggers",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Weapon Store: Twin Wooden Daggers ($70, Dwarves)",
        "category": "attack_player_multiplier",
        "trigger_timing": 8,
        "calculation": "each target.score = target.score * 0.75",
        "explanation_template": "Twin Wooden Daggers: {player} score {before} × 0.75 = {after}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_BRIBE",
        "rule_name": "Bribe",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — General Store: Bribe ($40). Fairies are immune.",
        "category": "attack_zeroing",
        "trigger_timing": 8,
        "calculation": "kicker.score = 0 (Fairies immune)",
        "explanation_template": "Bribe: {player} (kicker) score {before} → 0. Fairies immune.",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_ADRENALINE_POTION",
        "rule_name": "Adrenaline Potion",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Apothecary: Adrenaline Potion ($25)",
        "category": "attack_player_multiplier",
        "trigger_timing": 8,
        "calculation": "target.score = target.score * 1.25",
        "explanation_template": "Adrenaline Potion: {player} score {before} × 1.25 = {after}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_WOODEN_AXE",
        "rule_name": "Wooden Axe",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Weapon Store: Wooden Axe ($70, Halflings)",
        "category": "attack_score_replacement",
        "trigger_timing": 8,
        "calculation": "Among 3 targets, highest scorer's score = lowest scorer's score",
        "explanation_template": "Wooden Axe: {player} (highest) score {before} replaced by lowest scorer's {after}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ATK_MERCENARIES",
        "rule_name": "Mercenaries",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — General Store: Mercenaries ($40)",
        "category": "attack_player_multiplier",
        "trigger_timing": 8,
        "calculation": "each rookie starter.score = score * 1.5",
        "explanation_template": "Mercenaries: rookie {player} score {before} × 1.5 = {after}",
        "approval_status": "confirmed",
    },
    # ── Perks ─────────────────────────────────────────────────────────────────
    {
        "rule_id": "PERK_ARMY_SERGEANT",
        "rule_name": "Army Sergeant (Soldier L1)",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Soldier Perk: Army Sergeant",
        "category": "perk_player_multiplier",
        "trigger_timing": 8,
        "calculation": "highest_strength_position_player.score *= 1.30",
        "explanation_template": "Army Sergeant: {player} (top {position}) {before} × 1.30 = {after}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "PERK_MILITIA",
        "rule_name": "Militia (Soldier L2)",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Soldier Perk: Militia",
        "category": "perk_teamwide_percentage",
        "trigger_timing": 11,
        "calculation": "team_score += sum(active_player_scores) * 0.20",
        "explanation_template": "Militia: all active players +20% = +{bonus}",
        "approval_status": "provisional",
        "commissioner_note": "AMB-002: Militia timing and base disputed. Provisional: applies to adjusted player scores in step 11.",
    },
    {
        "rule_id": "PERK_ATTACK_OF_SQUIRES",
        "rule_name": "Attack of the Squires (Soldier L2)",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Soldier Perk: Attack of the Squires",
        "category": "perk_bench_contribution",
        "trigger_timing": 9,
        "calculation": "team_score += bench_total * 0.5",
        "explanation_template": "Attack of the Squires: ½ bench score {bench} = +{bonus}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "PERK_RESERVE_FORCES",
        "rule_name": "Reserve Forces (Strategist L2)",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Strategist Perk: Reserve Forces",
        "category": "perk_bench_contribution",
        "trigger_timing": 9,
        "calculation": "team_score += top_bench_player.score; top_bench_player.immune = true",
        "explanation_template": "Reserve Forces: {player} (top bench {score}) added + immune to attacks",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "PERK_SALARY_BONUS",
        "rule_name": "Salary Bonus (Financier L1)",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Financier Perk: Salary Bonus",
        "category": "perk_gold",
        "trigger_timing": 9,
        "calculation": "gold += 2 * bench_total",
        "explanation_template": "Salary Bonus: 2 × bench {bench} = +{gold} gold",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "PERK_MARTYR",
        "rule_name": "Martyr (Necromancer L1)",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Necromancer Perk: Martyr",
        "category": "perk_player_multiplier",
        "trigger_timing": 8,
        "calculation": "chosen_player.score *= 2; chosen_player.dies_at_week_end = true",
        "explanation_template": "Martyr: {player} scores double ({before} × 2 = {after}), dies at week's end",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "PERK_SOUL_REAPER",
        "rule_name": "Soul Reaper (Necromancer L1)",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Necromancer Perk: Soul Reaper",
        "category": "perk_death",
        "trigger_timing": 16,
        "calculation": "for each opponent starter with raw_score <= 5: player.dead = true",
        "explanation_template": "Soul Reaper: {player} raw ≤ 5, dies at week's end",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "PERK_TEAM_UNITY",
        "rule_name": "Team Unity (Druid L2)",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Druid Perk: Team Unity",
        "category": "perk_teamwide_percentage",
        "trigger_timing": 11,
        "calculation": "if all starters home or all away: team_score += raw_team_score * 0.40",
        "explanation_template": "Team Unity: all {location} games → +40% raw = +{bonus}",
        "approval_status": "confirmed",
    },
    # ── Gold ──────────────────────────────────────────────────────────────────
    {
        "rule_id": "GOLD_RACE_INCOME",
        "rule_name": "Race Gold Income",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Earning Gold table",
        "category": "race_gold",
        "trigger_timing": 13,
        "calculation": "Human: 5×QB | Elf: 2×top2WR+10 | Dwarf: 3×top2IDP+10 | Halfling: 4×topRB | Fairy: 5×K+50 | Troll: 5×topTE+20",
        "explanation_template": "{race} race gold: {formula} = {gold}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "GOLD_PURCHASE",
        "rule_name": "Gold Deduction for Purchase",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Shopping in Town",
        "category": "gold_transaction",
        "trigger_timing": 14,
        "calculation": "gold -= item_cost",
        "explanation_template": "{team} spent {cost} gold on {item}. Balance: {balance}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "GOLD_INSUFFICIENT",
        "rule_name": "Insufficient Gold Validation",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Fines: 'Buying an item without sufficient gold'",
        "category": "validation",
        "trigger_timing": 14,
        "calculation": "if gold < cost: reject purchase",
        "explanation_template": "{team} has {gold} gold, needs {cost}. Purchase rejected.",
        "approval_status": "confirmed",
    },
    # ── Rulings / Deaths ──────────────────────────────────────────────────────
    {
        "rule_id": "RULING_SCORE_ADJ",
        "rule_name": "Commissioner Score Adjustment",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Commissioner authority",
        "category": "manual_ruling",
        "trigger_timing": 17,
        "calculation": "team_score += adjustment",
        "explanation_template": "Commissioner ruling: {description}. Score adjusted by {adj}",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "DEATH_POST_WEEK",
        "rule_name": "Post-Week Player Death",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — Quests: Dead Players",
        "category": "death",
        "trigger_timing": 16,
        "calculation": "player.is_dead = true; player must be dropped immediately",
        "explanation_template": "{player} died via {cause} at week's end. Must be dropped.",
        "approval_status": "confirmed",
    },
    {
        "rule_id": "ITEM_INSPIRING_SERMON",
        "rule_name": "Inspiring Sermon",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — General Store: Inspiring Sermon ($30)",
        "category": "fixed_team_bonus",
        "trigger_timing": 12,
        "calculation": "if all active players play Sunday: team_score += 10",
        "explanation_template": "Inspiring Sermon: all active players Sunday → +10 points",
        "approval_status": "provisional",
        "commissioner_note": "Sunday-game verification requires game schedule data. Provisional until confirmed.",
    },
    {
        "rule_id": "ITEM_GAMBLERS_LUCK",
        "rule_name": "Gambler's Luck",
        "version": "v1",
        "source_citation": "https://footbolzano.com/rules/ — General Store: Gambler's Luck ($20)",
        "category": "rounding",
        "trigger_timing": 18,
        "calculation": "team_score = ceil(team_score / 10) * 10",
        "explanation_template": "Gambler's Luck: {before} rounded up to nearest 10 = {after}",
        "approval_status": "confirmed",
    },
]
